site_name: "Muhammad Ahmad"

theme:
  name: "material"
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: 'indigo'
      accent: 'deep orange'
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: 'indigo'
      accent: 'deep orange'
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: "Roboto"
    code: "Roboto Mono"
  logo: "images/logo.png"
  features:
    - navigation.footer
    - navigation.expand        # default behavior
    - navigation.instant       # smooth page loads
    - navigation.sections      # section-based nav (optional)
    - navigation.top           # “back to top” button
    - navigation.tracking      # highlight current heading
    - navigation.tabs.sticky   # sticky tabs
    - navigation.indexes      # index page

nav:
  - Home: index.md
  - Projects: projects.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - css/extra.css

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/muhammad-ahmad-b6a04736/
    - icon: fontawesome/brands/github
      link: https://www.github.com/ahmadfsbd
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/ehm_ud
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@ehm_ud

copyright: Copyright &copy; 2025 Muhammad Ahmad. All rights reserved.
