site_name: "Muhammad Ahmad"

theme:
  name: "material"
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: 'indigo'
      accent: 'deep orange'
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: 'indigo'
      accent: 'deep orange'
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: "Roboto"
    code: "Roboto Mono"
  logo: "images/logo.png"
  features:
    - navigation.footer
    - navigation.instant
    - navigation.top
    - navigation.tracking
    - navigation.tabs.sticky
    - navigation.tabs        # 🔑 Enables top-level tabs
    - navigation.tabs.sticky # (optional) Tabs stay visible when scrolling
    - content.code.copy

nav:
  - Intro: index.md
  - Skills & Tech Stack: skills.md
  - Certifications: certifications.md
  - Achievements & Honors: achievements.md
  - Career Journey:
      - Career Journey: career/index.md
  - Blog / Tutorials:
      - Blog Home: blog/index.md
      - First Post: blog/post1.md
      - Second Post: blog/post2.md
  - Photography: photography.md
  - Contact: contact.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_css:
  - css/extra.css

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/muhammad-ahmad-b6a04736/
    - icon: fontawesome/brands/github
      link: https://www.github.com/ahmadfsbd
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/ehm_ud
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@ehm_ud

copyright: Copyright &copy; 2025 Muhammad Ahmad. All rights reserved.
