name: Deploy MkDocs to GitHub Pages

on:
  # Deploy automatically on push to main and allow manual runs
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install MkDocs + Material
        run: pip install mkdocs mkdocs-material

      - name: Build site
        run: mkdocs build --clean    # cleans local ./site directory

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site        # output folder
          publish_branch: gh-pages   # branch to publish
          force_orphan: true         # recreate branch from scratch
          enable_jekyll: false       # avoid Jekyll processing
